siteName: L'autre école
productionUrl: https://www.autre-ecole.org
htmlHead: |-
  <link rel="stylesheet" href="/assets/styles/local.css">
cssHead: |-

languages:
  - code: fr
    name: Français
    customUrlPrefix:
      prefix: ""
    status: published
    isCmsDefault: true
    isWebsiteDefault: true
collections:
  - articles
lang: fr
