siteName: poko demo
productionUrl: https://m4rrc0.github.io/poko-website-builder
logo: /_images/POKO-logo-RVB-01.jpg
htmlHead: ""
cssHead: ""
languages:
  - code: en
    status: published
    name: English
    isCmsDefault: false
    isWebsiteDefault: false
    customUrlPrefix: null
  - code: fr
    status: published
    name: Fran√ßais
    isCmsDefault: true
    isWebsiteDefault: true
    customUrlPrefix:
      prefix: ""
collections:
  - articles
  - events
  - courses
  - places
  - products
  - reviews
metadata:
  image: ""
